### ISSUE TITLE
Focus spell component missing

### ISSUE THREAD

**Issue by dmarcuse** [galdiuz/nethys-search#6]
It's possible to filter by spell components, but only verbal, somatic, and material seem to be currently supported. There's also the "focus" component (not to be confused with focus spells), which is very infrequently used but might still be worth including - e.g. the [Plane Shift](https://2e.aonprd.com/Spells.aspx?ID=222) spell.

**Comment by galdiuz** [comment]
Thanks for the report. I'll make sure to add the component to the list of filterable components.

**Comment by dmarcuse** [comment]
Awesome, thank you!
